### ISSUE TITLE
P3 DEMO: Increasing the height of the heatmap, covers the buttons in Demo

### ISSUE THREAD

**Issue by Aileen-H** [predixdesignsystem/px-vis-heatmap#36]
In Chrome, performing testing.

Expected Behavior: Buttons in demo should shift downward, when height of grid increased.

Actual Behavior: Grid overlays buttons in demo, when height increased.
![screen shot 2018-03-05 at 4 11 31 pm](https://user-images.githubusercontent.com/21231643/37007078-5d863934-2090-11e8-9ef7-651ec2fcdea2.png)

**Comment by drewharvey** [comment]
This is because the container is fixed height.  I was getting strange behavior with the auto-resizing and the container height, so I fixed the height.  Need to discuss with chart team.

**Comment by Aileen-H** [comment]
GE can fix when we implement the demo.
