### ISSUE TITLE
Heatmap: Axis Label Spacing 

### ISSUE THREAD

**Issue by andrealperry** [predixdesignsystem/px-vis-heatmap#38]
**Current:**
![screen shot 2018-03-06 at 11 40 18 am](https://user-images.githubusercontent.com/30873778/37054246-2a3b62c2-2133-11e8-8f60-9e04482192ea.png)

**Expected:**
![screen shot 2018-03-06 at 11 39 05 am](https://user-images.githubusercontent.com/30873778/37054234-21fc0fb2-2133-11e8-8d05-aec41a34066e.png)

**Comment by drewharvey** [comment]
@nonmetalhail are there props for this type of spacing in the axis component?

If possible, we should update the demo to use these values.

**Comment by drewharvey** [comment]
Got these spacing values as close as possible in commit 5b930ee687bcac1602dd0180a6b5a40ddc2f705c.
