### ISSUE TITLE
P3 DEMO: Move Correlation Plot & Confusion Matrix to tabs

### ISSUE THREAD

**Issue by andrealperry** [predixdesignsystem/px-vis-heatmap#39]
Move Correlation Plot & Confusion Matrix to tabs.

**Currently buttons below the heat map update the graph:**
![screen shot 2018-03-08 at 10 01 39 am](https://user-images.githubusercontent.com/30873778/37167812-d658ab20-22b7-11e8-998c-a718c7daadf0.png)

**Move the options to be accessible via tabs:**
![screen shot 2018-03-08 at 10 01 44 am](https://user-images.githubusercontent.com/30873778/37167808-d26a717e-22b7-11e8-8708-4e95cfffdaf2.png)

**Comment by Aileen-H** [comment]
GE will implement in the demo as needed. Can be closed.

**Comment by drewharvey** [comment]
Re-opening, closed on accident (still need QA to verify fix).
