### ISSUE TITLE
Confusion Matrix not included

### ISSUE THREAD

**Issue by andrealperry** [predixdesignsystem/px-vis-heatmap#40]
The confusion matrix is not currently included.

A reference screenshot from the spec:
![screen shot 2018-03-08 at 10 07 19 am](https://user-images.githubusercontent.com/30873778/37168054-8445468a-22b8-11e8-934f-1bbea85e8847.png)

**Comment by drewharvey** [comment]
PR #37 added the custom column api which can be used to create the accuracy column for the confusion matrix.

The actual work for this issue is to create a demo page with a heatmap setup like the above spec.

**Comment by drewharvey** [comment]
Re-opening, closed on accident (still need QA to verify fix).
