### ISSUE TITLE
Tooltip/Pop-over Spacing not correct

### ISSUE THREAD

**Issue by andrealperry** [predixdesignsystem/px-vis-heatmap#41]
Current:
![screen shot 2018-03-08 at 10 12 35 am](https://user-images.githubusercontent.com/30873778/37168298-465907e8-22b9-11e8-8500-1d2830a66ad3.png)

**Correct tooltip spacing:**
![screen shot 2018-03-08 at 10 11 24 am](https://user-images.githubusercontent.com/30873778/37168321-5c7f19c2-22b9-11e8-8f9f-4dd80febfe27.png)

**Correct pop-over spacing:**
![screen shot 2018-03-08 at 10 11 19 am](https://user-images.githubusercontent.com/30873778/37168334-6482171e-22b9-11e8-8ae3-ff55e6a498ea.png)

**Comment by drewharvey** [comment]
There is no obvious way to define inner padding for px-tooltip.  Two options to fix:
 * px-tooltip exposes css var or props to define padding
 * we wrap the contents in an additional container and add some amount of padding so it gets to be around 20px total

The first options makes more sense and is exact, but either will work.  For now I will set as `waiting on external dependency`.

**Comment by drewharvey** [comment]
Made some simple changes that brings the padding to about 20px.  I also changed the text size and spacing to match the spec. 2c90ba2181df2999a3b3e76f78748acc6151ec8a
