### ISSUE TITLE
Does not render in Polymer 1

### ISSUE THREAD

**Issue by nonmetalhail** [predixdesignsystem/px-vis-heatmap#44]
Chart does not appear to work in Polymer 1.

**Comment by drewharvey** [comment]
Briefly looked into this.  If you set chartData again it will render as expected.  For some reason it is getting invalid x and y return values when it tries to draw the first time.

**Comment by drewharvey** [comment]
This appears to have been fixed.  When I run with `polymer serve` and select Polymer 1, chart comes up as expected.

To view Polymer 1 and 2 versions, run the following (command line) in the project directory:

```
polymer install --variants
polymer serve
```

Navigate to the url provided by the commands and click the Polymer 1 url:

![polymer-1](https://user-images.githubusercontent.com/2496955/37627410-75f248ee-2b91-11e8-9047-c4a25eb6bd3f.jpg)
